#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDB221A6900000011 (keithp@debian.org)
#
Name     : xproto
Version  : 7.0.31
Release  : 13
URL      : http://xorg.freedesktop.org/releases/individual/proto/xproto-7.0.31.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/proto/xproto-7.0.31.tar.gz
Source99 : http://xorg.freedesktop.org/releases/individual/proto/xproto-7.0.31.tar.gz.sig
Summary  : Xproto headers
Group    : Development/Tools
License  : MIT
Requires: xproto-doc
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : xmlto

%description
X Window System Core Protocol
This package provides the headers and specification documents defining
the X Window System Core Protocol, Version 11.

%package dev
Summary: dev components for the xproto package.
Group: Development
Provides: xproto-devel

%description dev
dev components for the xproto package.


%package dev32
Summary: dev32 components for the xproto package.
Group: Default
Requires: xproto-dev

%description dev32
dev32 components for the xproto package.


%package doc
Summary: doc components for the xproto package.
Group: Documentation

%description doc
doc components for the xproto package.


%prep
%setup -q -n xproto-7.0.31
pushd ..
cp -a xproto-7.0.31 build32
popd

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484497146
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1484497146
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/DECkeysym.h
/usr/include/X11/HPkeysym.h
/usr/include/X11/Sunkeysym.h
/usr/include/X11/X.h
/usr/include/X11/XF86keysym.h
/usr/include/X11/XWDFile.h
/usr/include/X11/Xalloca.h
/usr/include/X11/Xarch.h
/usr/include/X11/Xatom.h
/usr/include/X11/Xdefs.h
/usr/include/X11/Xfuncproto.h
/usr/include/X11/Xfuncs.h
/usr/include/X11/Xmd.h
/usr/include/X11/Xos.h
/usr/include/X11/Xos_r.h
/usr/include/X11/Xosdefs.h
/usr/include/X11/Xpoll.h
/usr/include/X11/Xproto.h
/usr/include/X11/Xprotostr.h
/usr/include/X11/Xthreads.h
/usr/include/X11/Xw32defs.h
/usr/include/X11/Xwindows.h
/usr/include/X11/Xwinsock.h
/usr/include/X11/ap_keysym.h
/usr/include/X11/keysym.h
/usr/include/X11/keysymdef.h
/usr/lib64/pkgconfig/xproto.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/pkgconfig/32xproto.pc
/usr/lib32/pkgconfig/xproto.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/xproto/*
